import type { Resource, SuggestResult } from '../types.js';

/** Markdown export (spec §10, the v1 export target). */
export function toMarkdown(topic: string, result: SuggestResult): string {
  const lines: string[] = [
    `# Supporting resources: ${topic}`,
    '',
    `> Generated by Bowerbird. Every resource below was retrieved and`,
    `> verified — none are LLM-generated citations.`,
    '',
  ];
  for (const r of result.resources) {
    lines.push(...resourceBlock(r), '');
  }
  const degraded = Object.entries(result.componentHealth).filter(([, v]) => v !== 'ok');
  if (degraded.length) {
    lines.push(
      '---',
      '',
      `_Degraded components this run: ${degraded
        .map(([k, v]) => `${k} (${v})`)
        .join(', ')}._`,
      '',
    );
  }
  return lines.join('\n');
}

function resourceBlock(r: Resource): string[] {
  const meta: string[] = [`**${label(r.format)}**`];
  if (r.year) meta.push(String(r.year));
  if (r.authors.length) meta.push(r.authors.slice(0, 3).join(', '));
  if (r.venue) meta.push(r.venue);
  meta.push(`source: ${r.sourceType}`);
  meta.push(`verification: ${r.verification}`);
  if (r.licensing !== 'unknown') meta.push(`licensing: ${r.licensing}`);
  if (r.accessibilityNotes.length) meta.push(r.accessibilityNotes.join(', '));
  if (r.commerciallyInterested) meta.push('⚠ commercially interested');

  const lines = [`## [${r.title}](${r.url})`, '', meta.join(' · ')];
  if (r.annotation.text) {
    const provenance =
      r.annotation.source === 'llm' ? 'Rationale (generated)' : 'Description (extracted)';
    lines.push('', `${provenance}: ${r.annotation.text}`);
  }
  return lines;
}

function label(format: Resource['format']): string {
  return format === 'white-paper' ? 'white paper' : format;
}
